http_port: 8080

threshold: 20

user_endpoints: 20

jwt:
  private_key: "mysupersecretkey"
  expire_time: 30

mongodb:
  database: "policeman"
  host: "localhost"
  port: 27017

worker:
  timeout: 20
  workers: 5